### PR TITLE
adding back Understand basics...

### PR DESCRIPTION
**Pull request by shawna-slh**
... key stuff from previous version
https://www.w3.org/WAI/EO/Drafts/Improving2012.html#start

I think this is important since a key audience of this page is people who don't know about web accessibility.

### CODE REVIEW

**Comment by iadawn** [comment]
I don't have a huge problem adding this in but I do wonder a bit about the value in regards to the key audience and purpose of the document.

If the reader doesn't know about accessibility and they have a need to improve their site NOW, is it realistic for them to be heading off to learn about accessibility and be able to know enough to progress with improvements?

Realistically in this case my advice would be to find an 'expert'.

**Comment by shawna-slh** [comment]
I think EOWG has agreed that ideally everyone involved as at least a basic knowledge of accessibility. Those two pages are fairly short and skimmable.

In the previous version we mentioned "experts" a few places:
"Many organizations hire accessibility specialists to evaluate their website. Accessibility specialists can also provide guidance on retrofitting your site, including general recommendations on approach and priorities, specific recommendations for repairing each barrier identified, and guidance on the knowledge and skills needed for the repairs."
"It is often best to combine educating existing staff with bringing in outside expertise, either hiring additional staff or engaging consultants. A qualified accessibility expert can save time and effort in the long run by providing:
The latest best practices for accessibility solutions
First-hand experience of how people with disabilities interact with the Web"
"Involving users with disabilities and having accessibility specialists evaluate your planned repairs can catch any problems before they are propagated throughout your site."

Looks like this version includes at least one of those.

**Comment by iadawn** [comment]
I think I still have some concerns with addin this in here. If a reader needs the resources being linked to, there is no way they are going to be able to undertake any of the other work. They are in the wrong place from the start and I worry that suggesting a few introductory pages may either leave them none-the-wiser, give the false impression that this stuff is easy,  or leave them with the overriding panic that there is simply way too much.

If a reader does not fall into the above category, then they don't need this stuff.

It may be this is something that can be brought to EO for further discussion.

**Comment by iadawn** [comment]
This was addressed with cd20208

**Pull request closed without merging**
